export const defaultEnding = {
  en: {
    shareSurvey: "Share Survey",
    defaultEnding: "Default Ending",
    reloadOrRedirect: "Reload or Direct Button",
    buttonText: "Submit",
    redirectTo: "Redirect To",
    autoReload: "Auto Reload",
    reloadTimeInSeconds: "Reload Time in Seconds",
    missingAnotherLink: "Link is required",
    default: "Default",
    surveyLink: "Survey Link (Reaload the Survey)",
    resultsLink: "Results Link",
    anotherLink: "Another Link",
  },
  de: {
    shareSurvey: "Umfrage teilen",
    defaultEnding: "Standardende",
    reloadOrRedirect: "Neu laden oder Direkt-Button",
    buttonText: "Absenden",
    redirectTo: "Weiterleiten zu",
    autoReload: "Automatisch neu laden",
    reloadTimeInSeconds: "Neu laden Zeit in Sekunden",
    missingAnotherLink: "Link ist erforderlich",
    default: "Standard",
    surveyLink: "Umfrage-Link (Neu laden der Umfrage)",
    resultsLink: "Ergebnis-Link",
    anotherLink: "Anderer Link",
  },
};
