export const login = {
  en: {
    username: "Username",
    password: "Password",
    login: "Login",
    welcome: "Welcome",
    enterUsername: "Enter Username",
    enterPassword: "Enter Password",
    enterUsernameAndPassword: "Enter Username and Password",
    invalidUsername: "Invalid Username",
    invalidPassword: "Invalid Password",
    userNotFound: "User not found",
    passwordNotMatch: "Passwords do not match",
    selectLanguage: "Select Language",
  },
  de: {
    username: "Benutzername",
    password: "Passwort",
    login: "Anmelden",
    welcome: "Willkommen",
    enterUsername: "Benutzername eingeben",
    enterPassword: "Passwort eingeben",
    enterUsernameAndPassword: "Benutzername und Passwort eingeben",
    invalidUsername: "Ungültiger Benutzername",
    invalidPassword: "Ungültiges Passwort",
    userNotFound: "Benutzer nicht gefunden",
    passwordNotMatch: "Passwörter stimmen nicht überein",
    selectLanguage: "Sprache auswählen",
  },
};
