export const surveyErrorsTranslations = {
  en: {
    invalidWorkspaceId: "Invalid workspace ID.",
    workspaceNotFound: "Workspace not found.",
    chooseWorkspace: "Please choose a workspace.",
    surveyNotFound: "Survey not found.",
    invalidSurveyId: "Invalid survey ID.",
    titleRequired: "Survey title is required.",
    titleExists: "A survey with this title already exists.",
    urlRequired: "Survey URL is required.",
    invalidUrl: "Invalid survey URL format.",
    urlExists: "A survey with this URL already exists.",
    selectedWorkspaceNotFoundDoesntExist:
      "The workspace you selected does not exist.",
    targetWorkspaceNotFound: "Target workspace not found.",
    surveyTitleRequired: "survey title is required",
    surveyTitleTooLong: "survey title is too long",
    urlTooLong: "URL is too long",
    urlInvalid: "URL must contain only letters and numbers",
  },
  de: {
    invalidWorkspaceId: "Ungültige Arbeitsbereichs-ID.",
    workspaceNotFound: "Arbeitsbereich nicht gefunden.",
    chooseWorkspace: "Bitte wählen Sie einen Arbeitsbereich aus.",
    surveyNotFound: "Umfrage nicht gefunden.",
    invalidSurveyId: "Ungültige Umfrage-ID.",
    titleRequired: "Umfragetitel ist erforderlich.",
    titleExists: "Eine Umfrage mit diesem Titel existiert bereits.",
    urlRequired: "Umfrage-URL ist erforderlich.",
    invalidUrl: "Ungültiges URL-Format für die Umfrage.",
    urlExists: "Eine Umfrage mit dieser URL existiert bereits.",
    selectedWorkspaceNotFoundDoesntExist:
      "Der ausgewählte Arbeitsbereich existiert nicht.",
    targetWorkspaceNotFound: "Zielarbeitsbereich nicht gefunden.",
    surveyTitleRequired: "Ungültiges ist erforderlich",
    surveyTitleTooLong: "Ungültiges ist zu lang",
    urlTooLong: "URL ist zu lang",
    urlInvalid: "URL darf nur Buchstaben und Zahlen enthalten",
  },
};
