export const groupTranslations = {
  en: {
    notAMemberOfGroup: "User isn't not a member of this group",
    groupNotFound: "Group not found",
    userNotFound: "User not found",
    groupNameRequired: "Group name is required",
    groupNameTooLong: "Group name is too long",
    invitedUsersRequired: "Invited users are required",
    invitedUsersTooLong: "Invited users are too long",
    userIsAlreadyAMember: "User is already a member",
    cantinviteYourSelf: "You can't invite yourself",
    notAMemberOfAnyGroup: "User isn't a member of any group",
  },
  de: {
    notAMemberOfGroup: "Benutzer ist nicht Mitglied dieser Gruppe",
    groupNotFound: "Gruppe nicht gefunden",
    userNotFound: "Benutzer nicht gefunden",
    groupNameRequired: "Gruppenname ist erforderlich",
    groupNameTooLong: "Gruppenname ist zu lang",
    invitedUsersRequired: "Eingeladene Benutzer sind erforderlich",
    invitedUsersTooLong: "Eingeladene Benutzer sind zu lang",
    userIsAlreadyAMember: "Benutzer ist bereits Mitglied",
    cantinviteYourSelf: "Du kannst dich nicht selbst einladen",
    notAMemberOfAnyGroup: "Der Benutzer ist kein Mitglied einer Gruppe",
  },
};